[package]
name = "nlink"
version = "1.0.0"
description = "nlink-ng Evo link (the rest of the core is C++)"
authors = [
  "Ben Schattinger <developer@lights0123.com>",
  "Ryan <ryan@freyja.pw>",
]
license = "GPL-3.0"
repository = "https://github.com/RyanHakurei/nlink-ng"
edition = "2021"

[lib]
name = "nlink"
crate-type = ["staticlib", "rlib"]

[dependencies]
libc = "0.2"
png = "0.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(not(target_os = "android"))'.dependencies]
rusb = "0.6.4"
